.\" See LICENSE file for copyright and license details.
.Dd August 29, 2023
.Dt LSW 1
.Os lsw @VERSION@
.Sh NAME
.Nm lsw
.Nd list X11 windows
.Sh SYNOPSIS
.Nm
.Op Ar window ...
.Nm lswmenu
.Op Ar window ...
.Op Ar dmenu_options ...
.Sh DESCRIPTION
.Nm lsw
prints the XID, class and title of each child of each
.Op window .
If none are given the root window is used.
.Pp
.Nm lswmenu
is a script which lists windows with the ability to
select and jump to the specified one.
.Sh SEE ALSO
.Xr dmenu 1
