.\" See LICENSE file for copyright and license details.
.Dd August 29, 2023
.Dt LSW 1
.Os lsw @VERSION@
.Sh NAME
.Nm lsw
.Nd list X11 windows
.Sh SYNOPSIS
.Nm
.Op Ar window ...
.Nm lswmenu
.Op Ar window ...
.Op Ar dmenu_options ...
.Sh DESCRIPTION
.Nm lsw
prints the XID, class and title of each child of each
.Op window .
If none are given the root window is used.
.Pp
.Nm lswmenu
is a simple Perl script which uses
.Nm lsw ,
.Xr dmenu 1 ,
and
.Xr wmctrl 1
or
.Xr xdotool 1
to list windows, select and jump to the specified one.
.Sh ENVIRONMENT
The following environment variables affect the execution of
.Nm lswmenu :
.Bl -tag -width indent
.It Ev LSWMENU_WIN_JUMP
If the environment variable
.Ev LSWMENU_WIN_JUMP
is set to
.Dq xdotool ,
use
.Xr xdotool 1
to jump to the specified window after it was selected on
.Xr dmenu 1
invocation.
Also, can be set to
.Dq wmctrl ,
or unset, which means
.Xr wmctrl 1
will be used by default.
.El
.Sh SEE ALSO
.Xr dmenu 1
