.\" See LICENSE file for copyright and license details.
.Dd August 29, 2023
.Dt LSW 1
.Os
.\" ==================================================================
.Sh NAME
.Nm lsw
.Nd list X11 windows
.\" ==================================================================
.Sh SYNOPSIS
.Nm
.Op Ar window ...
.Nm lswmenu
.Op Ar \-verbose
.Op Ar \-wmctrl | \-xdotool | \-xdo
.Op Ar window ...
.Op Ar dmenu_options ...
.\" ==================================================================
.Sh DESCRIPTION
.Nm lsw
prints the XID, class and title of each child of each
.Ar window .
If none are given the root window is used.
.Pp
.Nm lswmenu
is a simple Perl script which uses
.Nm lsw ,
.Xr dmenu 1 ,
and
.Xr wmctrl 1 Ns / Ns Xr xdotool 1 Ns / Ns Xr xdo 1
to list windows, select and jump to the specified one.
Use
.Ar \-verbose
option to see what is being done, and
.Ar \-xdotool
or
.Ar \-xdo
option to use
.Xr xdotool 1
or
.Xr xdo 1
utility as window jumper instead of the default
.Xr wmctrl 1 .
.\" ==================================================================
.Sh SEE ALSO
.Xr dmenu 1
.\" vim: cc=72 tw=70
.\" End of file.
